export const TRIPS = [
  {
    id: 1,
    from: "Bergen",
    to: "Hirtshals",
    departure_time: "08:00",
    arrival_time: "17:30",
    duration: "9h 30m",
    operator: "Fjordline",
    price: "450 NOK",
    days: ["monday", "wednesday", "friday", "sunday"],
  },
  {
    id: 2,
    from: "Hirtshals",
    to: "Bergen",
    departure_time: "19:00",
    arrival_time: "08:00",
    duration: "9h 30m",
    operator: "Fjordline",
    price: "450 NOK",
    days: ["monday", "wednesday", "friday", "sunday"],
  },
  {
    id: 3,
    from: "Kristiansand",
    to: "Hirtshals",
    departure_time: "14:30",
    arrival_time: "18:15",
    duration: "3h 45m",
    operator: "Color Line",
    price: "122 NOK",
    days: ["tuesday", "thursday", "saturday"],
  },
  {
    id: 4,
    from: "Hirtshals",
    to: "Kristiansand",
    departure_time: "09:30",
    arrival_time: "13:25",
    duration: "3h 55m",
    operator: "Color Line",
    price: "122 NOK",
    days: ["tuesday", "thursday", "saturday"],
  },
  {
    id: 5,
    from: "Stavanger",
    to: "Bergen",
    departure_time: "09:00",
    arrival_time: "14:30",
    duration: "5h 30m",
    operator: "Fjordline",
    price: "350 NOK",
    days: [
      "monday",
      "tuesday",
      "wednesday",
      "thursday",
      "friday",
      "saturday",
      "sunday",
    ],
  },
  {
    id: 6,
    from: "Bergen",
    to: "Stavanger",
    departure_time: "16:00",
    arrival_time: "21:30",
    duration: "5h 30m",
    operator: "Fjordline",
    price: "350 NOK",
    days: [
      "monday",
      "tuesday",
      "wednesday",
      "thursday",
      "friday",
      "saturday",
      "sunday",
    ],
  },
  {
    id: 7,
    from: "Stavanger",
    to: "Kristiansand",
    departure_time: "07:00",
    arrival_time: "11:30",
    duration: "4h 30m",
    operator: "Fjordline",
    price: "280 NOK",
    days: ["monday", "wednesday", "friday"],
  },
  {
    id: 8,
    from: "Kristiansand",
    to: "Stavanger",
    departure_time: "13:00",
    arrival_time: "17:30",
    duration: "4h 30m",
    operator: "Fjordline",
    price: "280 NOK",
    days: ["monday", "wednesday", "friday"],
  },
];
